# Generated by Django 3.0.2 on 2020-02-18 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='title',
        ),
        migrations.RemoveField(
            model_name='education',
            name='title',
        ),
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
