# Generated by Django 3.0.2 on 2020-02-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20200218_0454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='image',
            new_name='content',
        ),
    ]
