# Generated by Django 3.0.2 on 2020-02-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20200218_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='remark',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='remark',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='remark',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='remark',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
