# Generated by Django 3.0.2 on 2020-02-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20200218_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='remark',
            field=models.CharField(default='Not defined', max_length=30),
        ),
        migrations.AlterField(
            model_name='education',
            name='remark',
            field=models.CharField(default='Not defined', max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='remark',
            field=models.CharField(default='Not defined', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='remark',
            field=models.CharField(default='Not defined', max_length=30),
        ),
    ]
