# Generated by Django 3.0.2 on 2020-02-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20200218_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(default='Not defined', max_length=30)),
                ('image', models.ImageField(upload_to='', verbose_name='assets/image')),
            ],
        ),
    ]
