# Generated by Django 3.0.2 on 2020-02-18 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20200218_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='education',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='home',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='message',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='remark',
        ),
    ]
