# Generated by Django 3.0.2 on 2020-02-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='assets/image'),
        ),
    ]
