# Generated by Django 3.0.2 on 2020-02-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_auto_20200218_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(upload_to='assets/image'),
        ),
    ]
