# Generated by Django 3.0.2 on 2020-02-18 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0002_auto_20200218_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='how',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='image',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='now',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='why',
            name='remark',
        ),
    ]
