# Generated by Django 3.0.2 on 2020-02-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0004_conference_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='how',
            name='title',
            field=models.CharField(default='temp', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='now',
            name='title',
            field=models.CharField(default='NOW', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='why',
            name='title',
            field=models.CharField(default='NOW', max_length=30),
            preserve_default=False,
        ),
    ]
