# Generated by Django 3.0.2 on 2020-02-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0006_titlejournal_titlepaper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitleJournal',
            new_name='TitleTechnique',
        ),
    ]
