# Generated by Django 3.0.2 on 2020-02-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='remark',
        ),
    ]
