# Generated by Django 3.0.2 on 2020-02-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0002_remove_network_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='image',
            field=models.ImageField(upload_to='assets/image'),
        ),
    ]
